services:
  proxy:
    image: nginx:1.21.3-alpine
    container_name: proxy
    restart: always
    ports:
      - "443"
      - "80"
    depends_on:
      - app-frontend
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
  app-frontend:
    image: __APP_IMAGE__
    container_name: app-frontend
    restart: always
    expose:
      - "3000"