version: '3'

services:
  app-frontend:
    image: __APP_IMAGE__
    container_name: app-frontend
    restart: always
    environment:
      - 'VIRTUAL_HOST=rasseki.com'
      - 'VIRTUAL_PORT=3000'
      - 'LETSENCRYPT_HOST=rasseki.com'
      - 'LETSENCRYPT_EMAIL=dmitrydpaliy@gmail.com'
      - 'PORT=3000'
    expose:
      - '3000'

  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    container_name: nginx-proxy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro

  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    environment:
      - 'NGINX_PROXY_CONTAINER=nginx-proxy'
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  conf:
  vhost:
  html:
  dhparam:
  certs:
  acme:
