name: checkup
on:
  pull_request:
    branches:
      - master

jobs:
  dependencies:
    name: Install dependencies
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - run: npm ci
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-cache-node_modules-${{ hashFiles('**/package-lock.json') }}

  lint:
    name: Prettier and ESlint checkup
    runs-on: ubuntu-20.04
    needs: dependencies
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-cache-node_modules-${{ hashFiles('**/package-lock.json') }}
      - run: npm run lint

  ts-check:
    name: Typescript checkup
    runs-on: ubuntu-20.04
    needs: dependencies
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-cache-node_modules-${{ hashFiles('**/package-lock.json') }}
      - run: npm run check
